using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace FEB.EventSourcing.Snapshots.Generator;

[Generator]
public sealed class AutoSnapshotGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var results = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (n, _) => n is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
                transform: static (ctx, _) => TryBuild(ctx))
            .Where(r => r is not null)
            .Select((r, _) => r!)
            .Collect();

        var assemblyName = context.CompilationProvider
            .Select(static (c, _) => c.AssemblyName ?? "Assembly");

        context.RegisterSourceOutput(results.Combine(assemblyName), static (spc, input) =>
        {
            var (allResults, asmName) = input;

            foreach (var r in allResults)
            foreach (var d in r.Diagnostics)
                spc.ReportDiagnostic(d);

            // De-duplicate models across all aggregates: shared nested types (e.g. Address
            // in two aggregates) must be generated only once.
            var models = allResults
                .Where(r => r.RootModel is not null)
                .SelectMany(r => r.AllModels)
                .GroupBy(m => $"{m.Namespace}.{m.SnapshotTypeName}")
                .Select(g => g.First())
                .ToImmutableArray();

            foreach (var m in models)
            {
                var hint = $"{m.Namespace.Replace('.', '_')}_{m.SnapshotTypeName}.g.cs";
                spc.AddSource(hint, GenerateSource(m));
            }

            // DI-Modul: explizite Registrierung aller Metadaten statt AppDomain-Scan.
            if (models.Length > 0)
                spc.AddSource("SnapshotMetadataModule.g.cs", GenerateModuleSource(models, asmName));
        });
    }

    private static BuildResult? TryBuild(GeneratorSyntaxContext ctx)
    {
        var classSyntax = (ClassDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(classSyntax);
        if (symbol is not INamedTypeSymbol aggregate)
            return null;

        if (!HasAttribute(aggregate, "AutoSnapshotAttribute"))
            return null;

        var diags = ImmutableArray.CreateBuilder<Diagnostic>();

        var collector = new ModelCollector(diags);
        var rootModel = collector.BuildModelForType(aggregate, isRootAggregate: true, classSyntax.Identifier.GetLocation());

        if (rootModel is null)
            return new BuildResult(null,  diags.ToImmutable(), ImmutableArray<SnapshotModel>.Empty);

        if (rootModel.Properties.Length == 0)
        {
            diags.Add(Diagnostic.Create(
                Diagnostics.NoSnapshotProperties,
                classSyntax.Identifier.GetLocation(),
                aggregate.Name));
        }

        return new BuildResult(rootModel, diags.ToImmutable(), collector.Models);
    }

    private static string GenerateSource(SnapshotModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Linq;");
        sb.AppendLine("using FEB.EventSourcing.Snapshots;");

        if (!string.IsNullOrWhiteSpace(model.Namespace))
        {
            sb.Append("namespace ").Append(model.Namespace).AppendLine(";");
            sb.AppendLine();
        }

        // Snapshot DTO
        sb.AppendLine($"public sealed class {model.AggregateName}Snapshot");
        sb.AppendLine("{");
        foreach (var p in model.Properties)
        {
            var propType = GetSnapshotPropertyType(p);
            // "= default!" prevents CS8618 for non-nullable reference types in the consumer build
            sb.AppendLine($"    public {propType} {p.Name} {{ get; init; }} = default!;");
        }
        sb.AppendLine("}");
        sb.AppendLine();

        // Snapshot Meta
        sb.AppendLine($"internal class {model.AggregateName}SnapshotMeta : ISnapshotMetadata");
        sb.AppendLine("{");
        sb.AppendLine($"    public global::System.Type AggregateType => typeof({model.AggregateName});");
        sb.AppendLine($"    public global::System.Type SnapshotType => typeof({model.SnapshotTypeName});");

        sb.AppendLine($"    public object CreateSnapshot(object aggregate)");
        sb.AppendLine($"            => (({model.AggregateName})aggregate).CreateSnapshot();");

        sb.AppendLine($"    public void RestoreSnapshot(object aggregate, object snapshot)");
        sb.AppendLine($"            => (({model.AggregateName})aggregate)");
        sb.AppendLine($"                .RestoreFromSnapshot(({model.SnapshotTypeName})snapshot);");

        sb.AppendLine($"    public int Version => {model.Version};");
        sb.AppendLine("}");
        sb.AppendLine();

        // Aggregate Partial
        sb.AppendLine($"public partial class {model.AggregateName}");
        sb.AppendLine("{");

        sb.AppendLine($"    public {model.AggregateName}Snapshot CreateSnapshot()");
        sb.AppendLine("        => new()");
        sb.AppendLine("        {");

        foreach (var p in model.Properties)
            sb.AppendLine($"            {GenerateCreateExpression(p)}");


        sb.AppendLine("        };");
        sb.AppendLine();

        sb.AppendLine($"    public void RestoreFromSnapshot({model.AggregateName}Snapshot snapshot)");
        sb.AppendLine("    {");

        foreach (var p in model.Properties)
        {
            foreach (var line in GenerateRestoreStatements(p))
                sb.AppendLine($"        {line}");
        }

        sb.AppendLine("    }");

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateModuleSource(ImmutableArray<SnapshotModel> models, string assemblyName)
    {
        var sanitized = new string(assemblyName.Select(c => char.IsLetterOrDigit(c) ? c : '_').ToArray());

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace FEB.EventSourcing.Snapshots.Generated;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>All snapshot metadata generated in this assembly - for explicit DI registration without an assembly scan.</summary>");
        sb.AppendLine($"public static class SnapshotMetadataModule_{sanitized}");
        sb.AppendLine("{");
        sb.AppendLine("    public static global::System.Collections.Generic.IReadOnlyList<global::FEB.EventSourcing.Snapshots.ISnapshotMetadata> CreateAll()");
        sb.AppendLine("        => new global::FEB.EventSourcing.Snapshots.ISnapshotMetadata[]");
        sb.AppendLine("        {");
        foreach (var m in models)
        {
            var ns = string.IsNullOrWhiteSpace(m.Namespace) ? "" : $"{m.Namespace}.";
            sb.AppendLine($"            new global::{ns}{m.AggregateName}SnapshotMeta(),");
        }
        sb.AppendLine("        };");
        sb.AppendLine("}");

        return sb.ToString();
    }

    static string GetSnapshotPropertyType(SnapshotProperty p)
    {
        return p.Kind switch
        {
            SnapshotKind.Direct => p.TypeName,

            SnapshotKind.Object => p.IsNullable
                ? $"{p.NestedModel!.SnapshotTypeName}?"
                : p.NestedModel!.SnapshotTypeName,

            SnapshotKind.List => BuildListType(p),

            _ => p.TypeName
        };

        static string BuildListType(SnapshotProperty p)
        {
            // List<primitive> stays List<primitive>
            if (p.NestedModel is null)
                return p.TypeName;

            var elementSnapshot = p.NestedModel.SnapshotTypeName;
            return p.IsNullable
                ? $"global::System.Collections.Generic.List<{elementSnapshot}>?"
                : $"global::System.Collections.Generic.List<{elementSnapshot}>";
        }
    }

    private static IEnumerable<string> GenerateRestoreStatements(SnapshotProperty p)
    {
        switch (p.Kind)
        {
            case SnapshotKind.Direct:
                yield return $"this.{p.Name} = snapshot.{p.Name};";
                break;

            case SnapshotKind.Object:
                yield return $"if (snapshot.{p.Name} is null)";
                yield return $"    this.{p.Name} = null;";
                yield return $"else";
                yield return $"{{";
                yield return $"    this.{p.Name} ??= new {p.TypeName}();";
                yield return $"    this.{p.Name}.RestoreFromSnapshot(snapshot.{p.Name});";
                yield return $"}}";
                break;

            case SnapshotKind.List when p.NestedModel is null:
                // List<primitive>: direct copy, no element snapshots
                yield return $"this.{p.Name} = snapshot.{p.Name}?.ToList()";
                yield return $"    ?? new global::System.Collections.Generic.List<{p.ElementTypeName}>();";
                break;

            case SnapshotKind.List:
                yield return $"this.{p.Name} = snapshot.{p.Name}?";
                yield return $"    .Select(x =>";
                yield return $"    {{";
                yield return $"        var item = new {p.ElementTypeName}();";
                yield return $"        item.RestoreFromSnapshot(x);";
                yield return $"        return item;";
                yield return $"    }})";
                yield return $"    .ToList()";
                yield return $"    ?? new global::System.Collections.Generic.List<{p.ElementTypeName}>();";
                break;
        }
    }

    private static string GenerateCreateExpression(SnapshotProperty p)
    {
        // Read defensively via "?."; for non-nullable target properties suppress the
        // resulting NRT warning with "!" (the runtime guard stays in place).
        var suppress = p.IsNullable ? "" : "!";

        return p.Kind switch
        {
            SnapshotKind.Direct
                => $"{p.Name} = this.{p.Name},",

            SnapshotKind.Object
                => $"{p.Name} = this.{p.Name}?.CreateSnapshot(){suppress},",

            SnapshotKind.List when p.NestedModel is null
                => $"{p.Name} = this.{p.Name}?.ToList(){suppress},",

            SnapshotKind.List
                => $"{p.Name} = this.{p.Name}?.Select(x => x.CreateSnapshot()).ToList(){suppress},",

            _ => throw new InvalidOperationException()
        };
    }

    private static bool HasAttribute(ISymbol symbol, string name)
        => symbol.GetAttributes().Any(a => a.AttributeClass?.Name == name);
}
